/**
 * forms_seed.js  M6 様式定義の初期データ
 *
 * 出典　各演習林の公開ページ（2026年8月19日 調査）
 * ★リンクは HTTP で実在を確認済み。41本すべて到達。
 * ★書類の分類（doc_type）と締切の構造化は、公開情報からの推定を含む。
 *   9月のヒアリングで各演習林に確認すること。
 *
 * 生成　_import_forms.py（このファイルは手で編集しない）
 */

var FORMS_SEED = [
 {
  "forest_id": "CHB",
  "form_code": "1",
  "name": "教育研究計画書",
  "doc_type": "計画書",
  "stage": "事前",
  "condition": "研究や実習等で千葉演習林を訪問して教育研究を行うとき",
  "each_time": false,
  "dl_base": "年度の初回利用日",
  "dl_type": "前月◯日まで",
  "dl_value": 20,
  "dl_min_days": null,
  "dl_note": "毎年度、第1回目の利用希望日の前月20日まで",
  "file_key": "CHB-FILE01",
  "file_type": "Excel",
  "url": "https://www.uf.a.u-tokyo.ac.jp/chiba/utilization/教育研究計画書+データ利用申請書_20220101版.xlsx",
  "source_url": "https://www.uf.a.u-tokyo.ac.jp/chiba/utilization/index.html"
 },
 {
  "forest_id": "CHB",
  "form_code": "2",
  "name": "データ利用申請書",
  "doc_type": "データ利用",
  "stage": "事前",
  "condition": "千葉演習林が保管する未公開のデータ・資料を利用するとき（希望者のみ記入）",
  "each_time": false,
  "dl_base": "年度の初回利用日",
  "dl_type": "前月◯日まで",
  "dl_value": 20,
  "dl_min_days": null,
  "dl_note": "教育研究計画書と同時（第1回目利用の前月20日まで）",
  "file_key": "CHB-FILE01",
  "file_type": "Excel（上記計画書と同一ファイル）",
  "url": "https://www.uf.a.u-tokyo.ac.jp/chiba/utilization/教育研究計画書+データ利用申請書_20220101版.xlsx",
  "source_url": "https://www.uf.a.u-tokyo.ac.jp/chiba/utilization/index.html"
 },
 {
  "forest_id": "CHB",
  "form_code": "3",
  "name": "利用申込書",
  "doc_type": "申込書",
  "stage": "利用の都度",
  "condition": "訪問して利用するとき（常に）",
  "each_time": true,
  "dl_base": "利用開始日",
  "dl_type": "◯日前まで",
  "dl_value": 10,
  "dl_min_days": null,
  "dl_note": "利用希望日の10日前まで",
  "file_key": "CHB-FILE02",
  "file_type": "Excel",
  "url": "https://www.uf.a.u-tokyo.ac.jp/chiba/utilization/利用申込書（1・2・3）_20230101版.xlsx",
  "source_url": "https://www.uf.a.u-tokyo.ac.jp/chiba/utilization/index.html"
 },
 {
  "forest_id": "CHB",
  "form_code": "4",
  "name": "利用時届出書",
  "doc_type": "届出",
  "stage": "利用の都度",
  "condition": "訪問して利用するとき（常に）",
  "each_time": true,
  "dl_base": "利用開始日",
  "dl_type": "◯日前まで",
  "dl_value": 10,
  "dl_min_days": null,
  "dl_note": "利用希望日の10日前まで",
  "file_key": "CHB-FILE02",
  "file_type": "Excel（利用申込書と同一ファイル）",
  "url": "https://www.uf.a.u-tokyo.ac.jp/chiba/utilization/利用申込書（1・2・3）_20230101版.xlsx",
  "source_url": "https://www.uf.a.u-tokyo.ac.jp/chiba/utilization/index.html"
 },
 {
  "forest_id": "CHB",
  "form_code": "5",
  "name": "緊急連絡先名簿",
  "doc_type": "緊急連絡先",
  "stage": "利用の都度",
  "condition": "訪問して利用するとき（常に）",
  "each_time": true,
  "dl_base": "利用開始日",
  "dl_type": "◯日前まで",
  "dl_value": 10,
  "dl_min_days": null,
  "dl_note": "利用希望日の10日前まで",
  "file_key": "CHB-FILE02",
  "file_type": "Excel（利用申込書と同一ファイル）",
  "url": "https://www.uf.a.u-tokyo.ac.jp/chiba/utilization/利用申込書（1・2・3）_20230101版.xlsx",
  "source_url": "https://www.uf.a.u-tokyo.ac.jp/chiba/utilization/index.html"
 },
 {
  "forest_id": "CHB",
  "form_code": "6",
  "name": "安全チェックリスト（参考）",
  "doc_type": "参考資料",
  "stage": "記載なし",
  "condition": "使用を推奨（提出義務の記載なし）",
  "each_time": false,
  "dl_base": "記載なし",
  "dl_type": "記載なし",
  "dl_value": null,
  "dl_min_days": null,
  "dl_note": "記載なし",
  "file_key": "CHB-FILE03",
  "file_type": "PDF",
  "url": "https://www.uf.a.u-tokyo.ac.jp/chiba/utilization/anzenchekku_list.pdf",
  "source_url": "https://www.uf.a.u-tokyo.ac.jp/chiba/utilization/index.html"
 },
 {
  "forest_id": "HKD",
  "form_code": "A1",
  "name": "研究計画書",
  "doc_type": "計画書",
  "stage": "事前",
  "condition": "学術研究・卒業論文・調査観測試験・試料採取・データ利用・環境調査等のとき",
  "each_time": false,
  "dl_base": "利用開始日",
  "dl_type": "前月◯日まで",
  "dl_value": 20,
  "dl_min_days": null,
  "dl_note": "利用開始日の前月20日まで",
  "file_key": "HKD-FILE01",
  "file_type": "Word / PDF",
  "url": "https://www.uf.a.u-tokyo.ac.jp/hokuen/riyou/form_a1_2024.docx",
  "source_url": "https://www.uf.a.u-tokyo.ac.jp/hokuen/riyou/riyou.html"
 },
 {
  "forest_id": "HKD",
  "form_code": "A2",
  "name": "教育計画書",
  "doc_type": "計画書",
  "stage": "事前",
  "condition": "授業・実習・演習・体験学習・研修会・見学会・取材・写真資料提供等のとき",
  "each_time": false,
  "dl_base": "利用開始日",
  "dl_type": "前月◯日まで",
  "dl_value": 20,
  "dl_min_days": null,
  "dl_note": "利用開始日の前月20日まで",
  "file_key": "HKD-FILE02",
  "file_type": "Word / PDF",
  "url": "https://www.uf.a.u-tokyo.ac.jp/hokuen/riyou/form_a2_2024.docx",
  "source_url": "https://www.uf.a.u-tokyo.ac.jp/hokuen/riyou/riyou.html"
 },
 {
  "forest_id": "HKD",
  "form_code": "B",
  "name": "利用申込書",
  "doc_type": "申込書",
  "stage": "利用の都度",
  "condition": "常に（データ・標本利用のみで来訪しない場合は不要）",
  "each_time": true,
  "dl_base": "利用開始日",
  "dl_type": "◯日前まで",
  "dl_value": 10,
  "dl_min_days": null,
  "dl_note": "利用希望日の10日前まで",
  "file_key": "HKD-FILE03",
  "file_type": "Word / PDF",
  "url": "https://www.uf.a.u-tokyo.ac.jp/hokuen/riyou/form_b_2024.docx",
  "source_url": "https://www.uf.a.u-tokyo.ac.jp/hokuen/riyou/riyou.html"
 },
 {
  "forest_id": "HKD",
  "form_code": "C",
  "name": "利用者名簿・宿泊申込",
  "doc_type": "宿泊申込",
  "stage": "利用の都度",
  "condition": "来訪するとき／宿泊するとき",
  "each_time": true,
  "dl_base": "記載なし",
  "dl_type": "記載なし",
  "dl_value": null,
  "dl_min_days": null,
  "dl_note": "記載なし（様式Bとあわせて提出）",
  "file_key": "HKD-FILE04",
  "file_type": "Excel / PDF",
  "url": "https://www.uf.a.u-tokyo.ac.jp/hokuen/riyou/form_c_2025.xlsx",
  "source_url": "https://www.uf.a.u-tokyo.ac.jp/hokuen/riyou/riyou.html"
 },
 {
  "forest_id": "HKD",
  "form_code": "D",
  "name": "データ利用申請書",
  "doc_type": "データ利用",
  "stage": "事前",
  "condition": "北海道演習林所有のデータを利用するとき",
  "each_time": false,
  "dl_base": "記載なし",
  "dl_type": "記載なし",
  "dl_value": null,
  "dl_min_days": null,
  "dl_note": "A1・A2と同時",
  "file_key": "HKD-FILE05",
  "file_type": "Word / PDF",
  "url": "https://www.uf.a.u-tokyo.ac.jp/hokuen/riyou/form_d_202504.docx",
  "source_url": "https://www.uf.a.u-tokyo.ac.jp/hokuen/riyou/riyou.html"
 },
 {
  "forest_id": "HKD",
  "form_code": "E",
  "name": "標本・試料利用申請書",
  "doc_type": "標本・試料",
  "stage": "事前",
  "condition": "標本・試料（種子・苗木含む）の提供を受ける／利用するとき",
  "each_time": false,
  "dl_base": "記載なし",
  "dl_type": "記載なし",
  "dl_value": null,
  "dl_min_days": null,
  "dl_note": "A1・A2と同時",
  "file_key": "HKD-FILE06",
  "file_type": "Word / PDF",
  "url": "https://www.uf.a.u-tokyo.ac.jp/hokuen/riyou/form_e_202504.docx",
  "source_url": "https://www.uf.a.u-tokyo.ac.jp/hokuen/riyou/riyou.html"
 },
 {
  "forest_id": "HKD",
  "form_code": "F",
  "name": "無人航空機利用確認書",
  "doc_type": "無人航空機",
  "stage": "利用の都度",
  "condition": "演習林内で無人航空機を飛行させるとき",
  "each_time": true,
  "dl_base": "記載なし",
  "dl_type": "記載なし",
  "dl_value": null,
  "dl_min_days": null,
  "dl_note": "計画段階で提出可（未定部分は「未定」）＋利用毎に再提出",
  "file_key": "HKD-FILE07",
  "file_type": "Word / PDF",
  "url": "https://www.uf.a.u-tokyo.ac.jp/hokuen/riyou/form_f_jp_202504.docx",
  "source_url": "https://www.uf.a.u-tokyo.ac.jp/hokuen/riyou/riyou.html"
 },
 {
  "forest_id": "HKD",
  "form_code": "G",
  "name": "野生動物調査確認票",
  "doc_type": "野生動物",
  "stage": "事前",
  "condition": "脊椎動物を対象とする調査のとき",
  "each_time": false,
  "dl_base": "記載なし",
  "dl_type": "記載なし",
  "dl_value": null,
  "dl_min_days": null,
  "dl_note": "A1・A2と同時",
  "file_key": "HKD-FILE08",
  "file_type": "Excel / PDF",
  "url": "https://www.uf.a.u-tokyo.ac.jp/hokuen/riyou/form_g_2024.xlsx",
  "source_url": "https://www.uf.a.u-tokyo.ac.jp/hokuen/riyou/riyou.html"
 },
 {
  "forest_id": "HKD",
  "form_code": "H",
  "name": "化学物質・生物等持込み確認書",
  "doc_type": "化学物質",
  "stage": "利用の都度",
  "condition": "化学物質・生物等の持ち込みがあるとき",
  "each_time": true,
  "dl_base": "記載なし",
  "dl_type": "記載なし",
  "dl_value": null,
  "dl_min_days": null,
  "dl_note": "様式Bと同時、利用毎に再提出",
  "file_key": "HKD-FILE09",
  "file_type": "Excel / PDF",
  "url": "https://www.uf.a.u-tokyo.ac.jp/hokuen/riyou/form_h_2024.xlsx",
  "source_url": "https://www.uf.a.u-tokyo.ac.jp/hokuen/riyou/riyou.html"
 },
 {
  "forest_id": "HKD",
  "form_code": "1",
  "name": "成果の別刷・要旨",
  "doc_type": "成果",
  "stage": "利用後",
  "condition": "成果を公表したとき",
  "each_time": false,
  "dl_base": "成果の公表日",
  "dl_type": "記載なし",
  "dl_value": null,
  "dl_min_days": null,
  "dl_note": "成果公表時",
  "file_key": "",
  "file_type": "紙 または PDF",
  "url": "記載なし",
  "source_url": "https://www.uf.a.u-tokyo.ac.jp/hokuen/riyou/riyou.html"
 },
 {
  "forest_id": "HKD",
  "form_code": "2",
  "name": "利用報告（メール）",
  "doc_type": "報告",
  "stage": "利用後",
  "condition": "研究・教育利用をしたとき",
  "each_time": false,
  "dl_base": "記載なし",
  "dl_type": "記載なし",
  "dl_value": null,
  "dl_min_days": null,
  "dl_note": "利用後2年間、毎年1〜2月",
  "file_key": "",
  "file_type": "メール",
  "url": "記載なし",
  "source_url": "https://www.uf.a.u-tokyo.ac.jp/hokuen/riyou/riyou.html"
 },
 {
  "forest_id": "CHC",
  "form_code": "1",
  "name": "研究教育計画書",
  "doc_type": "計画書",
  "stage": "事前",
  "condition": "研究・教育目的で利用するとき",
  "each_time": false,
  "dl_base": "年度の初回利用日",
  "dl_type": "◯日前まで",
  "dl_value": 20,
  "dl_min_days": null,
  "dl_note": "年度の1回目の利用希望日の20日前まで（継続課題は10日前まで）",
  "file_key": "CHC-FILE01",
  "file_type": "Excel / PDF",
  "url": "http://www.uf.a.u-tokyo.ac.jp/chichibu/use/files/kenkyo,riyou_20260424.xlsx",
  "source_url": "http://www.uf.a.u-tokyo.ac.jp/chichibu/use/index.php"
 },
 {
  "forest_id": "CHC",
  "form_code": "2",
  "name": "利用申込書",
  "doc_type": "申込書",
  "stage": "利用の都度",
  "condition": "常に",
  "each_time": true,
  "dl_base": "年度の初回利用日",
  "dl_type": "◯日前まで",
  "dl_value": 20,
  "dl_min_days": null,
  "dl_note": "1回目は利用希望日の20日前まで（継続課題10日前）。2回目以降は教職員対応・宿泊を伴う場合10日前まで、伴わない場合5日前まで",
  "file_key": "CHC-FILE01",
  "file_type": "Excel / PDF",
  "url": "http://www.uf.a.u-tokyo.ac.jp/chichibu/use/files/kenkyo,riyou_20260424.xlsx",
  "source_url": "http://www.uf.a.u-tokyo.ac.jp/chichibu/use/index.php"
 },
 {
  "forest_id": "CHC",
  "form_code": "3",
  "name": "利用者名簿",
  "doc_type": "名簿",
  "stage": "利用の都度",
  "condition": "来訪するとき",
  "each_time": true,
  "dl_base": "記載なし",
  "dl_type": "記載なし",
  "dl_value": null,
  "dl_min_days": null,
  "dl_note": "（利用申込書と同じ）",
  "file_key": "CHC-FILE01",
  "file_type": "Excel / PDF",
  "url": "http://www.uf.a.u-tokyo.ac.jp/chichibu/use/files/kenkyo,riyou_20260424.xlsx",
  "source_url": "http://www.uf.a.u-tokyo.ac.jp/chichibu/use/index.php"
 },
 {
  "forest_id": "CHC",
  "form_code": "4",
  "name": "宿泊利用申込書",
  "doc_type": "宿泊申込",
  "stage": "利用の都度",
  "condition": "宿泊するとき",
  "each_time": true,
  "dl_base": "記載なし",
  "dl_type": "記載なし",
  "dl_value": null,
  "dl_min_days": null,
  "dl_note": "（利用申込書と同じ）",
  "file_key": "CHC-FILE01",
  "file_type": "Excel / PDF",
  "url": "http://www.uf.a.u-tokyo.ac.jp/chichibu/use/files/kenkyo,riyou_20260424.xlsx",
  "source_url": "http://www.uf.a.u-tokyo.ac.jp/chichibu/use/index.php"
 },
 {
  "forest_id": "CHC",
  "form_code": "5",
  "name": "無人航空機（UAV）飛行計画書",
  "doc_type": "計画書",
  "stage": "記載なし",
  "condition": "無人航空機（ドローン）を飛ばすとき",
  "each_time": false,
  "dl_base": "記載なし",
  "dl_type": "記載なし",
  "dl_value": null,
  "dl_min_days": null,
  "dl_note": "記載なし",
  "file_key": "CHC-FILE02",
  "file_type": "Excel / PDF",
  "url": "http://www.uf.a.u-tokyo.ac.jp/chichibu/use/files/UAV-keikaku_chichibu20230410.xlsx",
  "source_url": "http://www.uf.a.u-tokyo.ac.jp/chichibu/use/index.php"
 },
 {
  "forest_id": "TNS",
  "form_code": "1",
  "name": "田無演習林研究・教育利用申込書",
  "doc_type": "申込書",
  "stage": "事前",
  "condition": "研究で利用するとき／種苗の提供を希望するとき（常に）",
  "each_time": false,
  "dl_base": "利用開始日",
  "dl_type": "前月◯日まで",
  "dl_value": 15,
  "dl_min_days": null,
  "dl_note": "原則として利用予定日の前月15日まで",
  "file_key": "TNS-FILE01",
  "file_type": "Excel / PDF",
  "url": "https://www.uf.a.u-tokyo.ac.jp/tanashi/Word/application_for_research_and_education_ver230126.xlsx",
  "source_url": "https://www.uf.a.u-tokyo.ac.jp/tanashi/research.html"
 },
 {
  "forest_id": "TNS",
  "form_code": "2",
  "name": "利用者名簿・緊急時対応情報",
  "doc_type": "名簿",
  "stage": "利用の都度",
  "condition": "常に",
  "each_time": true,
  "dl_base": "当日",
  "dl_type": "記載なし",
  "dl_value": null,
  "dl_min_days": null,
  "dl_note": "利用開始日までになるべく早めに（利用開始当日に直接提出も可）",
  "file_key": "TNS-FILE02",
  "file_type": "Excel / PDF",
  "url": "https://www.uf.a.u-tokyo.ac.jp/tanashi/Word/user_list_ver221130.xlsx",
  "source_url": "https://www.uf.a.u-tokyo.ac.jp/tanashi/research.html"
 },
 {
  "forest_id": "AIC",
  "form_code": "1",
  "name": "研究教育計画書",
  "doc_type": "計画書",
  "stage": "事前",
  "condition": "研究目的で利用するとき（データ利用のみの場合も必要）",
  "each_time": false,
  "dl_base": "年度の初回利用日",
  "dl_type": "前月◯日まで",
  "dl_value": 20,
  "dl_min_days": null,
  "dl_note": "年度の第1回目の利用希望日の前月20日まで",
  "file_key": "AIC-FILE01",
  "file_type": "Excel",
  "url": "https://www.uf.a.u-tokyo.ac.jp/eri/wp/wp-content/uploads/2022/04/研究教育計画書_20220422.xlsx",
  "source_url": "https://www.uf.a.u-tokyo.ac.jp/eri/research-use/"
 },
 {
  "forest_id": "AIC",
  "form_code": "2",
  "name": "利用計画書",
  "doc_type": "計画書",
  "stage": "事前",
  "condition": "研究・教育以外の目的で利用するとき",
  "each_time": false,
  "dl_base": "年度の初回利用日",
  "dl_type": "前月◯日まで",
  "dl_value": 20,
  "dl_min_days": null,
  "dl_note": "年度の第1回目の利用希望日の前月20日まで",
  "file_key": "AIC-FILE02",
  "file_type": "Word",
  "url": "https://www.uf.a.u-tokyo.ac.jp/eri/wp/wp-content/uploads/2022/05/20180730利用計画書.docx",
  "source_url": "https://www.uf.a.u-tokyo.ac.jp/eri/edu-use/"
 },
 {
  "forest_id": "AIC",
  "form_code": "3",
  "name": "研究教育計画書（教育用）",
  "doc_type": "計画書",
  "stage": "事前",
  "condition": "教育目的で利用するとき",
  "each_time": false,
  "dl_base": "記載なし",
  "dl_type": "記載なし",
  "dl_value": null,
  "dl_min_days": null,
  "dl_note": "（教育利用ページに期限の明記なし）",
  "file_key": "AIC-FILE03",
  "file_type": "Word",
  "url": "https://www.uf.a.u-tokyo.ac.jp/eri/wp/wp-content/uploads/2020/04/研究教育計画書（教育用）.docx",
  "source_url": "https://www.uf.a.u-tokyo.ac.jp/eri/edu-use/"
 },
 {
  "forest_id": "AIC",
  "form_code": "4",
  "name": "利用申込書",
  "doc_type": "申込書",
  "stage": "利用の都度",
  "condition": "常に（許可取得後）",
  "each_time": true,
  "dl_base": "利用開始日",
  "dl_type": "期間内",
  "dl_value": 10,
  "dl_min_days": 90,
  "dl_note": "利用希望日の3ヶ月前から10日前まで",
  "file_key": "AIC-FILE04",
  "file_type": "Word",
  "url": "https://www.uf.a.u-tokyo.ac.jp/eri/image/common/apply/%E3%80%90%E8%A5%BF%E6%9A%A6%E3%81%AB%E5%A4%89%E6%9B%B4%E3%80%91HP%E5%88%A9%E7%94%A8%E7%94%B3%E8%BE%BC/201807%E5%88%A9%E7%94%A8%E7%94%B3%E8%BE%BC%E6%9B%B8.docx",
  "source_url": "https://www.uf.a.u-tokyo.ac.jp/eri/research-use/"
 },
 {
  "forest_id": "AIC",
  "form_code": "5",
  "name": "利用者名簿",
  "doc_type": "名簿",
  "stage": "利用の都度",
  "condition": "来訪するとき",
  "each_time": true,
  "dl_base": "利用開始日",
  "dl_type": "◯日前まで",
  "dl_value": 10,
  "dl_min_days": null,
  "dl_note": "利用申込書と同時（利用希望日の10日前まで）",
  "file_key": "AIC-FILE05",
  "file_type": "Excel",
  "url": "https://www.uf.a.u-tokyo.ac.jp/eri/wp/wp-content/uploads/2020/04/利用者名簿（日帰り・宿泊）_20200402.xlsx",
  "source_url": "https://www.uf.a.u-tokyo.ac.jp/eri/research-use/"
 },
 {
  "forest_id": "AIC",
  "form_code": "6",
  "name": "利用者全員の保険加入を証明する資料の写し",
  "doc_type": "保険",
  "stage": "利用の都度",
  "condition": "野外活動を含む利用のとき（参加者全員が傷害保険・レジャー保険等に加入していること）",
  "each_time": true,
  "dl_base": "利用開始日",
  "dl_type": "◯日前まで",
  "dl_value": 10,
  "dl_min_days": null,
  "dl_note": "利用申込書と同時（利用希望日の10日前まで）",
  "file_key": "",
  "file_type": "写し（形式の指定は記載なし）",
  "url": "記載なし（様式なし）",
  "source_url": "https://www.uf.a.u-tokyo.ac.jp/eri/research-use/"
 },
 {
  "forest_id": "AIC",
  "form_code": "7",
  "name": "データ利用に関する申請書",
  "doc_type": "データ利用",
  "stage": "事前",
  "condition": "生態水文学研究所のデータを利用するとき",
  "each_time": false,
  "dl_base": "記載なし",
  "dl_type": "記載なし",
  "dl_value": null,
  "dl_min_days": null,
  "dl_note": "研究教育計画書と同時",
  "file_key": "AIC-FILE06",
  "file_type": "Word / PDF",
  "url": "https://www.uf.a.u-tokyo.ac.jp/eri/file/Data_application_form.docx",
  "source_url": "https://www.uf.a.u-tokyo.ac.jp/eri/research-use/"
 },
 {
  "forest_id": "AIC",
  "form_code": "8",
  "name": "データを用いた成果の発表・投稿の通知書",
  "doc_type": "データ利用",
  "stage": "利用後",
  "condition": "データを用いた成果を発表・投稿するとき",
  "each_time": false,
  "dl_base": "記載なし",
  "dl_type": "記載なし",
  "dl_value": null,
  "dl_min_days": null,
  "dl_note": "記載なし",
  "file_key": "AIC-FILE07",
  "file_type": "Word",
  "url": "https://www.uf.a.u-tokyo.ac.jp/eri/image/common/apply/%E3%80%90%E8%A5%BF%E6%9A%A6%E3%81%AB%E5%A4%89%E6%9B%B4%E3%80%91HP%E5%88%A9%E7%94%A8%E7%94%B3%E8%BE%BC/tsuchisyo20181016.doc",
  "source_url": "https://www.uf.a.u-tokyo.ac.jp/eri/research-use/"
 },
 {
  "forest_id": "AIC",
  "form_code": "9",
  "name": "チェックシート・危険情報フィードバック報告書",
  "doc_type": "報告",
  "stage": "利用後",
  "condition": "常に（利用許可を受けた者）",
  "each_time": false,
  "dl_base": "利用終了日",
  "dl_type": "◯日以内",
  "dl_value": 7,
  "dl_min_days": null,
  "dl_note": "利用後7日以内",
  "file_key": "",
  "file_type": "Webフォーム / メール / Fax / 郵送",
  "url": "https://docs.google.com/forms/d/1uBUM2x3lFxq1J9Ob4iaeT5V7Z6iiidwDlNROkowDh8c/edit",
  "source_url": "https://www.uf.a.u-tokyo.ac.jp/eri/research-use/"
 },
 {
  "forest_id": "FJI",
  "form_code": "1",
  "name": "利用申込書",
  "doc_type": "申込書",
  "stage": "利用の都度",
  "condition": "すべての利用に必要",
  "each_time": true,
  "dl_base": "利用開始日",
  "dl_type": "◯日前まで",
  "dl_value": 7,
  "dl_min_days": null,
  "dl_note": "利用日の1週間前まで",
  "file_key": "FJI-FILE01",
  "file_type": "Excel / PDF",
  "url": "https://www.uf.a.u-tokyo.ac.jp/fuji/guide/application/riyou.xlsx",
  "source_url": "https://www.uf.a.u-tokyo.ac.jp/fuji/guide/"
 },
 {
  "forest_id": "FJI",
  "form_code": "2",
  "name": "利用者名簿",
  "doc_type": "名簿",
  "stage": "利用の都度",
  "condition": "すべての利用に必要（省略する場合は「利用者名簿省略願」）",
  "each_time": true,
  "dl_base": "利用開始日",
  "dl_type": "◯日前まで",
  "dl_value": 7,
  "dl_min_days": null,
  "dl_note": "利用日の1週間前まで",
  "file_key": "FJI-FILE02",
  "file_type": "Word / PDF",
  "url": "https://www.uf.a.u-tokyo.ac.jp/fuji/guide/application/list.docx",
  "source_url": "https://www.uf.a.u-tokyo.ac.jp/fuji/guide/"
 },
 {
  "forest_id": "FJI",
  "form_code": "3",
  "name": "利用者名簿省略願",
  "doc_type": "名簿",
  "stage": "利用の都度",
  "condition": "利用者名簿を省略するとき",
  "each_time": true,
  "dl_base": "利用開始日",
  "dl_type": "◯日前まで",
  "dl_value": 7,
  "dl_min_days": null,
  "dl_note": "利用日の1週間前まで",
  "file_key": "FJI-FILE03",
  "file_type": "Word / PDF",
  "url": "https://www.uf.a.u-tokyo.ac.jp/fuji/guide/application/omission.docx",
  "source_url": "https://www.uf.a.u-tokyo.ac.jp/fuji/guide/"
 },
 {
  "forest_id": "FJI",
  "form_code": "4",
  "name": "宿泊申込書",
  "doc_type": "宿泊申込",
  "stage": "利用の都度",
  "condition": "自炊宿舎（山中宿泊施設）を利用するとき",
  "each_time": true,
  "dl_base": "利用開始日",
  "dl_type": "◯日前まで",
  "dl_value": 7,
  "dl_min_days": null,
  "dl_note": "利用日の1週間前まで",
  "file_key": "FJI-FILE04",
  "file_type": "Word / PDF",
  "url": "https://www.uf.a.u-tokyo.ac.jp/fuji/guide/application/stay.docx",
  "source_url": "https://www.uf.a.u-tokyo.ac.jp/fuji/guide/"
 },
 {
  "forest_id": "FJI",
  "form_code": "5",
  "name": "教育研究計画書",
  "doc_type": "計画書",
  "stage": "事前",
  "condition": "研究・教育利用のとき",
  "each_time": false,
  "dl_base": "記載なし",
  "dl_type": "記載なし",
  "dl_value": null,
  "dl_min_days": null,
  "dl_note": "（初回申し込み時に提出。日付での期限の明記なし）",
  "file_key": "FJI-FILE05",
  "file_type": "Word / PDF",
  "url": "https://www.uf.a.u-tokyo.ac.jp/fuji/guide/application/plan.docx",
  "source_url": "https://www.uf.a.u-tokyo.ac.jp/fuji/guide/"
 },
 {
  "forest_id": "FJI",
  "form_code": "6",
  "name": "データ等使用願",
  "doc_type": "データ利用",
  "stage": "記載なし",
  "condition": "データの利用、動植物の採取を伴う利用のとき",
  "each_time": false,
  "dl_base": "記載なし",
  "dl_type": "記載なし",
  "dl_value": null,
  "dl_min_days": null,
  "dl_note": "記載なし",
  "file_key": "FJI-FILE06",
  "file_type": "Word / PDF",
  "url": "https://www.uf.a.u-tokyo.ac.jp/fuji/guide/application/Data.docx",
  "source_url": "https://www.uf.a.u-tokyo.ac.jp/fuji/guide/"
 },
 {
  "forest_id": "FJI",
  "form_code": "7",
  "name": "無人航空機（ドローン）関係書類一式",
  "doc_type": "無人航空機",
  "stage": "記載なし",
  "condition": "ドローン等の飛行を伴う利用のとき",
  "each_time": false,
  "dl_base": "記載なし",
  "dl_type": "記載なし",
  "dl_value": null,
  "dl_min_days": null,
  "dl_note": "記載なし",
  "file_key": "FJI-FILE07",
  "file_type": "ZIP（中身の様式名はページ上に記載なし）",
  "url": "https://www.uf.a.u-tokyo.ac.jp/fuji/guide/application/UAV.zip",
  "source_url": "https://www.uf.a.u-tokyo.ac.jp/fuji/guide/"
 },
 {
  "forest_id": "JUG",
  "form_code": "1",
  "name": "樹芸研究所利用申込書",
  "doc_type": "申込書",
  "stage": "利用の都度",
  "condition": "研究または教育利用目的で利用するとき",
  "each_time": true,
  "dl_base": "利用開始日",
  "dl_type": "期間内",
  "dl_value": 10,
  "dl_min_days": 90,
  "dl_note": "原則として利用希望日の3ヶ月前から10日前まで。ただし学生実習・研修会・試験地の設定・立木の伐採を必要とする計画および年間利用計画を有する場合は利用する月の前月20日まで",
  "file_key": "JUG-FILE01",
  "file_type": "Word / PDF",
  "url": "https://www.uf.a.u-tokyo.ac.jp/jyugei/riyojuge.docx",
  "source_url": "https://www.uf.a.u-tokyo.ac.jp/jyugei/facilities_use_ARI.html"
 },
 {
  "forest_id": "JUG",
  "form_code": "2",
  "name": "樹芸研究所研究教育計画書",
  "doc_type": "計画書",
  "stage": "事前",
  "condition": "学生実習・研修会・試験地の設定や立木の伐採を必要とする計画、および年間利用計画を有するとき",
  "each_time": false,
  "dl_base": "利用開始日",
  "dl_type": "前月◯日まで",
  "dl_value": 20,
  "dl_min_days": null,
  "dl_note": "利用する月の前月20日まで（利用申込書と併せて提出）",
  "file_key": "JUG-FILE02",
  "file_type": "Word / PDF",
  "url": "https://www.uf.a.u-tokyo.ac.jp/jyugei/planjuge.docx",
  "source_url": "https://www.uf.a.u-tokyo.ac.jp/jyugei/facilities_use_ARI.html"
 },
 {
  "forest_id": "JUG",
  "form_code": "3",
  "name": "無人航空機利用申請書類一式",
  "doc_type": "無人航空機",
  "stage": "記載なし",
  "condition": "無人航空機（ドローン）を使用した教育研究目的の利用のとき",
  "each_time": false,
  "dl_base": "記載なし",
  "dl_type": "記載なし",
  "dl_value": null,
  "dl_min_days": null,
  "dl_note": "記載なし",
  "file_key": "JUG-FILE03",
  "file_type": "ZIP（中身の様式名はページ上に記載なし）",
  "url": "https://www.uf.a.u-tokyo.ac.jp/jyugei/riyo_uav.zip",
  "source_url": "https://www.uf.a.u-tokyo.ac.jp/jyugei/facilities_use_ARI.html"
 },
 {
  "forest_id": "JUG",
  "form_code": "4",
  "name": "見学者名簿",
  "doc_type": "名簿",
  "stage": "利用の都度",
  "condition": "一般利用（大温室の見学）のとき",
  "each_time": true,
  "dl_base": "当日",
  "dl_type": "記載なし",
  "dl_value": null,
  "dl_min_days": null,
  "dl_note": "当日",
  "file_key": "",
  "file_type": "紙（大温室入口に設置）",
  "url": "記載なし（Web上の様式なし）",
  "source_url": "https://www.uf.a.u-tokyo.ac.jp/jyugei/facilities_use_ARI.html"
 }
];
